name: Release
on:
  push:
      tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --stacktrace
      - name: Get version from tag
        id: tag_name
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ steps.tag_name.outputs.version }}
      - name: Build and release on curseforge
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: curseforge --stacktrace
        env:
          CURSE_API_KEY: ${{ secrets.CF_API_TOKEN }}
          CHANGELOG: ${{ steps.changelog_reader.outputs.changes }}
      - name: Publish to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
